version: '3.8'

services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    restart: always

  kafka:
    image: confluentinc/cp-kafka:latest
    container_name: kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_BROKER_ID: 1
    depends_on:
      - zookeeper

  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    container_name: zookeeper
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181

  # elasticsearch:
  #   image: docker.elastic.co/elasticsearch/elasticsearch:8.5.1
  #   container_name: elasticsearch
  #   environment:
  #     - discovery.type=single-node
  #   ports:
  #     - "9200:9200"

  airflow-webserver:
    image: apache/airflow:2.10.4
    container_name: airflow-webserver
    environment:
      - AIRFLOW__CORE__SQL_ALCHEMY_CONN=mongodb://mongo:27017/airflow
    ports:
      - "8080:8080"
    volumes:
      - airflow_data:/opt/airflow
    depends_on:
      - mongodb
      - kafka
      # - elasticsearch
    
    command: airflow standalone

  # django:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile
  #   container_name: django
  #   ports:
  #     - "8000:8000"
  #   depends_on:
  #     - mongodb
  #     - kafka
  #     - elasticsearch

volumes:
  mongo_data:
  airflow_data:
